name: poetry-publish
on:
  release:
    types: [released]
env:
  PYTHON_VERSION: "3.13"
  POETRY_VERSION: "1.8.5"
  POETRY_VIRTUALENVS_IN_PROJECT: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }} --python ${{ env.PYTHON_VERSION }}
      - name: Cache poetry venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-${{ env.POETRY_VERSION }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.POETRY_VERSION }}--venv-
      - name: Install dependencies
        run: |
          poetry install --only main,docs --extras bs4
      - name: Create Documentation
        run: |
          poetry run python -m docs
      - name: Upload GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
      - name: Build and publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry version $(git describe --tags)
          poetry build
          poetry publish
